config/routes.rb
Rails.application.routes.draw do
  resources :positions
  resources :submissions 

  get '/submissions', to: 'submissions#index'
  resources :escapes
  resources :buckets
  resources :bags 
  devise_for :users 

  

  # Define the user_bag route after the bags resources
  get '/my_bag', to: 'bags#my_bag', as: 'my_bag'
  get '/my_bucket', to: 'buckets#my_bucket', as: 'my_bucket'

  post '/add_submission_to_bag/:id', to: 'bags#add_submission_to_bag', as: 'add_submission_to_bag'
  post '/add_position_to_bag/:id', to: 'bags#add_position_to_bag', as: 'add_position_to_bag'
  post '/add_escape_to_bag/:id', to: 'bags#add_escape_to_bag', as: 'add_escape_to_bag'


  post '/add_submission_to_bucket/:id', to: 'buckets#add_submission_to_bucket', as: 'add_submission_to_bucket'
  post '/add_position_to_bucket/:id', to: 'buckets#add_position_to_bucket', as: 'add_position_to_bucket'
  post '/add_escape_to_bucket/:id', to: 'buckets#add_escape_to_bucket', as: 'add_escape_to_bucket'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  root to: "home#index" 

end

app/models/position.rb
class Position < ApplicationRecord
   belongs_to :bag, optional: true
   belongs_to :bucket, optional: true
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  before_action :set_position, only: %i[ show edit update destroy ]
  

  # GET /positions or /positions.json
  def index
    @positions = Position.all
  end

  # GET /positions/1 or /positions/1.json
  def show
  end

  # GET /positions/new
  def new
    @position = Position.new
  end

  # GET /positions/1/edit
  def edit
  end

  # POST /positions or /positions.json
  def create
    @position = Position.new(position_params)

    respond_to do |format|
      if @position.save
        format.html { redirect_to position_url(@position), notice: "Position was successfully created." }
        format.json { render :show, status: :created, location: @position }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /positions/1 or /positions/1.json
  def update
    respond_to do |format|
      if @position.update(position_params)
        format.html { redirect_to position_url(@position), notice: "Position was successfully updated." }
        format.json { render :show, status: :ok, location: @position }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /positions/1 or /positions/1.json
  def destroy
    @position.destroy

    respond_to do |format|
      format.html { redirect_to positions_url, notice: "Position was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_position
      @position = Position.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def position_params
      params.require(:position).permit(:name, :description, :possible_submissions, :video_url)
    end
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/views/positions/_form.html.erb
<%= form_with(model: position) do |form| %>
  <% if position.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(position.errors.count, "error") %> prohibited this position from being saved:</h2>

      <ul>
        <% position.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :possible_submissions, style: "display: block" %>
    <%= form.text_area :possible_submissions %>
  </div>

  <div>
    <%= form.label :video_url, style: "display: block" %>
    <%= form.text_field :video_url %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/positions/edit.html.erb
<h1>Editing position</h1>

<%= render "form", position: @position %>

<br>

<div>
  <%= link_to "Show this position", @position %> |
  <%= link_to "Back to positions", positions_path %>
</div>

app/views/positions/index.html.erb
<div class="position">
  <div class="container">
    <div class="row pt-4">
      <% @positions.take(69).each do |position| %>
        <div class="col-md-4">
          <%= link_to position_path(position) do %>
            <div class="card mb-4" id="<%= dom_id position %>">
              <div class="card-body">
                <h5 class="card-title"><%= position.name %></h5>
                <p class="card-text">
                  <strong>Description:</strong> <%= position.description %> <br>
                  <strong>Possible Submissions:</strong> <%= position.possible_submissions %> <br>
                </p>
                <iframe loading='lazy' src="https://www.youtube.com/embed/<%= position.video_url %>?rel=0&autoplay=<%= params[:autoplay] || 0 %>" frameborder="0" allowfullscreen></iframe>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>


<style>
@import url('https://fonts.googleapis.com/css2?family=Righteous&display=swap');
@import url('https://fonts.googleapis.com/css2?family=Lato:wght@300&display=swap');

.position {
  background-image: url('https://images.unsplash.com/photo-1661090790202-2f9173c66362?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1770&q=80');
}

.position a:link{
text-decoration: none;
}

.container {
  -webkit-backdrop-filter: blur(16px) saturate(180%);
  background-color: rgba(17, 25, 40, 0.25);
  border-radius: 12px;
  border: 1px solid rgba(255, 255, 255, 0.125);  
  filter: drop-shadow(0 30px 10px rgba(0,0,0,0.125));
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content:center;
  text-align: center;
}

.card {
  background: transparent;
  border: none;
  border-radius: 20px;
  box-shadow: 2px 2px 8px rgba(0, 0, 0, 0.1);
  overflow: hidden;
  transition: all 0.3s ease-in-out;
  backdrop-filter: blur(15px);
  position: relative;
  padding: 1em;
  color: white;
  text-shadow: 1px 1px 3px rgba(0, 0, 0, 0.2);
}

.card:hover {
  transform: scale(1.05);
  box-shadow: 2px 2px 8px rgba(0, 0, 0, 0.3);
}

.card-body {
  padding: 1.25rem;
}

.card-title {
  font-family: 'Righteous', sans-serif;
  color: rgba(255,255,255,0.98);
  text-transform: uppercase;
  font-size: 2.4rem;
}

.card-text {
  font-family: 'Lato', sans-serif;
  font-size: 0.8rem;
  color: #fff;
  line-height: 150%;
  letter-spacing: 2px;
  text-transform: uppercase;
}

iframe {
  width: 100%;
  height: 200px;
}
</style>

app/views/positions/new.html.erb
<h1>New position</h1>

<%= render "form", position: @position %>

<br>

<div>
  <%= link_to "Back to positions", positions_path %>
</div>

app/views/positions/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="text-center">

<div class='position-description'> 
  <div class="card">
    <div class="card-title"> <h5><%= @position.name%> </h5></div>
    <hr>
    <div class="card-body">
<p class="text-black"> <%= @position.description%></p>
      </div>

  </div>
</div>
<iframe src="https://www.youtube.com/embed/<%=@position.video_url %>?rel=0&autoplay=<%= params[:autoplay] || 0 %>" frameborder="0" allowfullscreen></iframe>
</div>

<div class='container'>
 <div class="row">
  <div class="col"> </div>
  <div class="col"> </div>
  <div class="col"> </div>
  <div class="col"> </div>
  <div class="col d-flex justify-content-center">
    <%= button_to "Add to Bag", add_position_to_bag_path(@position), method: :post, class: "btn btn-primary" %>
  </div>
  <div class="col d-flex justify-content-center">
    <%= button_to "Add to Bucket", add_position_to_bucket_path(@position), method: :post, class: "btn btn-primary" %>
  </div>
  <div class="col d-flex justify-content-center">
    <%= link_to "Back to positions", positions_path, class: "btn btn-secondary" %>
  </div>
  <div class="col"> </div>
  <div class="col"> </div>
  <div class="col"> </div>
  <div class="col"> </div>
</div>

</div>

<style>
iframe {
  padding-bottom: 20px;
  width: 80%;
  height: 400px;
}
.card{
  background-color: #FFC23C;
  margin: auto;
  margin-bottom: 10px;
  width: 50%;
}
.card-title{
  margin-top: 10px;
}

</style>