config/routes.rb
Rails.application.routes.draw do
  resources :positions
  resources :submissions 

  get '/submissions', to: 'submissions#index'
  resources :escapes
  resources :buckets
  resources :bags 
  devise_for :users 

  

  # Define the user_bag route after the bags resources
  get '/my_bag', to: 'bags#my_bag', as: 'my_bag'
  get '/my_bucket', to: 'buckets#my_bucket', as: 'my_bucket'

  post '/add_submission_to_bag/:id', to: 'bags#add_submission_to_bag', as: 'add_submission_to_bag'
  post '/add_position_to_bag/:id', to: 'bags#add_position_to_bag', as: 'add_position_to_bag'
  post '/add_escape_to_bag/:id', to: 'bags#add_escape_to_bag', as: 'add_escape_to_bag'


  post '/add_submission_to_bucket/:id', to: 'buckets#add_submission_to_bucket', as: 'add_submission_to_bucket'
  post '/add_position_to_bucket/:id', to: 'buckets#add_position_to_bucket', as: 'add_position_to_bucket'
  post '/add_escape_to_bucket/:id', to: 'buckets#add_escape_to_bucket', as: 'add_escape_to_bucket'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  root to: "home#index" 

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    render
  end
end

app/views/home/_footer.html.erb
<footer class=" text-center text-light py-3">
  <p>© 2023 BJJ Co-Pilot</p>
</footer>


<style>

footer {
    color: white;
    
}
</style>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark pt-10">
  <a href="/" class="navbar-brand ">BJJ CO-PILOT</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'SUBMISSIONS', submissions_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
         <%= link_to 'POSITIONS', positions_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
         <%= link_to 'ESCAPES', escapes_path, class: "nav-link" %>
      </li>
    </ul>
    <ul class="navbar-nav ms-auto">
      <% if user_signed_in? %>
        <li class="nav-item" style="margin-right: 10px;">
          <span class="nav-link"><%= link_to 'MY BAG', my_bag_path, class: "text-white text-decoration-none" %></span>
        </li>
        <li class="nav-item" style="margin-right: 10px;">
          <span class="nav-link"><%= link_to 'MY BUCKET', my_bucket_path, class: "text-white text-decoration-none" %></span>
        </li>
        <div class='text-white pt-2'> Welcome <%= current_user.email %> </div>
        <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "btn btn-primary" %>
      <% else %>
        <%= button_to "Sign in", new_user_session_path, class: "btn btn-primary" %>
      <% end %>
    </ul>
  </div>
</nav>

<style>
.navbar-dark .navbar-nav .nav-link {
  color: #ffffff;
  text-decoration: none;
}

.navbar {
  box-shadow: 0px 2px 10px rgba(0, 0, 0, 0.15); /* adjust as necessary */
  padding-right: 20px;
}

.navbar-dark .navbar-nav .nav-link:hover {
  color: gold;
}

.bu

.navbar-brand{
  margin: 10px;
  font-weight: bold;
}

.nav-item {
  font-weight: bold;
}

</style>

app/views/home/index.html.erb
<div class="jumbotron text-center">
  <div class="container">
    <br>
    <div class="phrase">
    <h1 class="display-4 text-light"><b>Unleash Your Inner Champion!</b></h1>
  </div>
    <img width="64" height="64" src="https://img.icons8.com/external-icongeek26-linear-colour-icongeek26/64/external-kimono-martial-arts-icongeek26-linear-colour-icongeek26.png" alt="external-kimono-martial-arts-icongeek26-linear-colour-icongeek26"/>
    <p class="lead text-light">The ultimate tool for mastering BJJ techniques, tracking your progress, and sharing your skills with the community.</p>
    <a href="/users/sign_up" class="btn btn-primary btn-lg btn-custom">Join the Crew</a>
  </div>
</div>

<div class="container">
  <div class="row">
   <div class="col-md-6 d-flex justify-content-center align-items-center">
    <img class="move-right" src="https://img.icons8.com/emoji/96/bucket-emoji.png" alt="bucket"/>
</div>
    <div class="col-md-6">
      <br>
      <br>
      <br>
      <br>
      <br>
      <h2 class="mb-4 text-light">Discover and Save Techniques</h2>
      <p class='text-light' >Add techniques to <strong>"The Bucket"</strong>. These are techniques that you want to master. Exploration is made simple with our comprehensive feed of Brazilian Jiu Jitsu techniques, including submissions, positions, and escapes.</p>
    </div>
  </div>
  <hr>

  <div class="row my-5">
    <div class="col-md-6 order-md-2 d-flex justify-content-center align-items-center">
            <img class='move-left'width="80" height="80" src="https://img.icons8.com/office/80/bag-diagonal-view.png" alt="bag-diagonal-view"/>    </div>
    <div class="col-md-6 order-md-1">
       <br>
      <br>
      <br>
      <br>
      <br>
      <h2 class="mb-4 text-light">Track Your Progress with Ease</h2>
      <p class='text-light'>Add techniques you've mastered to <strong>"The Bag"</strong>. These are techniques you have executed in sparring or competition. Keep track of your journey to black belt. Keep tabs on what you're learning and how far you've come!</p>
    </div>
  </div>

   <hr class='hr2'>
  <div class="row my-5">
    <div class="col-md-6 justify-content-center align-items-center">
      <img class="move-right2" width="96" height="96" src="https://img.icons8.com/fluency/96/microsoft-people.png" alt="microsoft-people"/>
    </div>
    <div class="col-md-6">
       <br>
      <br>
      <br>
      <br>
      <br>
      <h2 class="mb-4 text-light">Elevate the Community</h2>
      <p class='text-light'>Join a community of BJJ enthusiasts and become a part of elevating the sport. Share your skills, gain
         new insights and help others reach their full potential. Unleash the full potential of your BJJ journey!</p>
    </div>
  </div>

  <hr>


</div>


<style>

  p{
    padding-top: 20px;
  }

  hr{
    width: 100%;  
    border-width: 20px 0px 0px; 
    transform: rotate(-3deg);
    margin-top: 80px;
    color: lightskyblue;
  }

  .hr2{
    width: 100%; 
    color: lightskyblue; 
    border-width: 20px 0px 0px;  
    transform: rotate(6deg);
    margin-top: 130px;
  }

  .phrase{
    padding-top: 80px;

  }

  h1{
    text-transform: uppercase;
    font-weight: 600;
    }

  .move-right {
    margin-top: 100px;
  }
  .move-left {
    margin-top: 100px;
  }

  .move-right2 {
    margin-top: 120px;
    margin-left: 250px; /* adjust this value as needed */
  }

body .container {
    padding-right: 0 !important;
    padding-left: 0 !important;
}

</style>