config/routes.rb
Rails.application.routes.draw do
  resources :positions
  resources :submissions 

  get '/submissions', to: 'submissions#index'
  resources :escapes
  resources :buckets
  resources :bags 
  devise_for :users 

  

  # Define the user_bag route after the bags resources
  get '/my_bag', to: 'bags#my_bag', as: 'my_bag'
  get '/my_bucket', to: 'buckets#my_bucket', as: 'my_bucket'

  post '/add_submission_to_bag/:id', to: 'bags#add_submission_to_bag', as: 'add_submission_to_bag'
  post '/add_position_to_bag/:id', to: 'bags#add_position_to_bag', as: 'add_position_to_bag'
  post '/add_escape_to_bag/:id', to: 'bags#add_escape_to_bag', as: 'add_escape_to_bag'


  post '/add_submission_to_bucket/:id', to: 'buckets#add_submission_to_bucket', as: 'add_submission_to_bucket'
  post '/add_position_to_bucket/:id', to: 'buckets#add_position_to_bucket', as: 'add_position_to_bucket'
  post '/add_escape_to_bucket/:id', to: 'buckets#add_escape_to_bucket', as: 'add_escape_to_bucket'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  root to: "home#index" 

end

app/models/submission.rb
class Submission < ApplicationRecord
   belongs_to :bag, optional: true
   belongs_to :bucket, optional: true
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  before_action :set_submission, only: %i[ show edit update destroy ]
  

  # GET /submissions or /submissions.json
  def index
    @submissions = Submission.all
  end

  # GET /submissions/1 or /submissions/1.json
  def show
      @submission = Submission.find(params[:id])
  end

  # GET /submissions/new
  def new
    @submission = Submission.new
  end


  # GET /submissions/1/edit
  def edit
  end

  # POST /submissions or /submissions.json
  def create
    @submission = Submission.new(submission_params)

    respond_to do |format|
      if @submission.save
        format.html { redirect_to submission_url(@submission), notice: "Submission was successfully created." }
        format.json { render :show, status: :created, location: @submission }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /submissions/1 or /submissions/1.json
  def update
    respond_to do |format|
      if @submission.update(submission_params)
        format.html { redirect_to submission_url(@submission), notice: "Submission was successfully updated." }
        format.json { render :show, status: :ok, location: @submission }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /submissions/1 or /submissions/1.json
  def destroy
    @submission.destroy

    respond_to do |format|
      format.html { redirect_to submissions_url, notice: "Submission was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_submission
      @submission = Submission.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def submission_params
      params.require(:submission).permit(:name, :description, :category, :difficulty, :from_position, :video_url)
    end
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/views/submissions/_form.html.erb
<%= form_with(model: submission) do |form| %>
  <% if submission.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(submission.errors.count, "error") %> prohibited this submission from being saved:</h2>

      <ul>
        <% submission.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :category, style: "display: block" %>
    <%= form.text_field :category %>
  </div>

  <div>
    <%= form.label :difficulty, style: "display: block" %>
    <%= form.text_field :difficulty %>
  </div>

  <div>
    <%= form.label :from_position, style: "display: block" %>
    <%= form.text_field :from_position %>
  </div>

  <div>
    <%= form.label :video_url, style: "display: block" %>
    <%= form.text_field :video_url %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/submissions/edit.html.erb
<h1>Editing submission</h1>

<%= render "form", submission: @submission %>

<br>

<div>
  <%= link_to "Show this submission", @submission %> |
  <%= link_to "Back to submissions", submissions_path %>
</div>

app/views/submissions/index.html.erb
<div class="submission">
  <div class="container">
    <div class="row pt-4">
      <% @submissions.take(69).each do |submission| %>
        <div class="col-md-4">
          <%= link_to submission_path(submission) do %>
            <div class="card mb-4" id="<%= dom_id submission %>">
              <div class="card-body">
                <h5 class="card-title"><%= submission.name %></h5>
                <p class="card-text">
                  <strong>Category:</strong> <%= submission.category %> <br>
                  <strong>Difficulty:</strong> <%= submission.difficulty %> <br>
                  <strong>From position:</strong> <%= submission.from_position %>
                </p>
                <iframe loading='lazy' src="https://www.youtube.com/embed/<%= submission.video_url %>?rel=0&autoplay=<%= params[:autoplay] || 0 %>" frameborder="0" allowfullscreen></iframe>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>


<style>
@import url('https://fonts.googleapis.com/css2?family=Righteous&display=swap');
@import url('https://fonts.googleapis.com/css2?family=Lato:wght@300&display=swap');

.submission {
  background-image: url('https://images.unsplash.com/photo-1660836685837-47651f406b30?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1770&q=80');
}

.submission a:link{
text-decoration: none;
}

.container {
  -webkit-backdrop-filter: blur(16px) saturate(180%);
  background-color: rgba(17, 25, 40, 0.25);
  border-radius: 12px;
  border: 1px solid rgba(255, 255, 255, 0.125);  
  filter: drop-shadow(0 30px 10px rgba(0,0,0,0.125));
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content:center;
  text-align: center;
}

.card {
  background: transparent;
  border: none;
  border-radius: 20px;
  box-shadow: 2px 2px 8px rgba(0, 0, 0, 0.1);
  overflow: hidden;
  transition: all 0.3s ease-in-out;
  backdrop-filter: blur(15px);
  position: relative;
  padding: 1em;
  color: white;
  text-shadow: 1px 1px 3px rgba(0, 0, 0, 0.2);
}

.card:hover {
  transform: scale(1.05);
  box-shadow: 2px 2px 8px rgba(0, 0, 0, 0.3);
}

.card-body {
  padding: 1.25rem;
}

.card-title {
  font-family: 'Righteous', sans-serif;
  color: rgba(255,255,255,0.98);
  text-transform: uppercase;
  font-size: 2.4rem;
}

.card-text {
  font-family: 'Lato', sans-serif;
  font-size: 0.8rem;
  color: #fff;
  line-height: 150%;
  letter-spacing: 2px;
  text-transform: uppercase;
}

iframe {
  width: 100%;
  height: 200px;
}
</style>

app/views/submissions/new.html.erb
<h1>New submission</h1>

<%= render "form", submission: @submission %>

<br>

<div>
  <%= link_to "Back to submissions", submissions_path %>
</div>

app/views/submissions/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="text-center">
<h1 class="text-white"><%= @submission.name %></h1>
<p class="text-white"> Category: <%= @submission.category%></p>
<iframe src="https://www.youtube.com/embed/<%=@submission.video_url %>?rel=0&autoplay=<%= params[:autoplay] || 0 %>" frameborder="0" allowfullscreen></iframe>
</div>

<div class='container'>
 <div class="row">
  <div class="col"> </div>
  <div class="col"> </div>
  <div class="col"> </div>
  <div class="col"> </div>
  <div class="col d-flex justify-content-center">
    <%= button_to "Add to Bag", add_submission_to_bag_path(@submission), method: :post, class: "btn btn-primary" %>
  </div>
  <div class="col d-flex justify-content-center">
    <%= button_to "Add to Bucket", add_submission_to_bucket_path(@submission), method: :post, class: "btn btn-primary" %>
  </div>
  <div class="col d-flex justify-content-center">
    <%= link_to "Back to submissions", submissions_path, class: "btn btn-secondary" %>
  </div>
  <div class="col"> </div>
  <div class="col"> </div>
  <div class="col"> </div>
  <div class="col"> </div>
</div>

</div>

<style>
iframe {
  padding-bottom: 20px;
  width: 80%;
  height: 400px;
}

</style>