config/routes.rb
Rails.application.routes.draw do
  resources :positions
  resources :submissions 

  get '/submissions', to: 'submissions#index'
  resources :escapes
  resources :buckets
  resources :bags 
  devise_for :users 

  

  # Define the user_bag route after the bags resources
  get '/my_bag', to: 'bags#my_bag', as: 'my_bag'
  get '/my_bucket', to: 'buckets#my_bucket', as: 'my_bucket'

  post '/add_submission_to_bag/:id', to: 'bags#add_submission_to_bag', as: 'add_submission_to_bag'
  post '/add_position_to_bag/:id', to: 'bags#add_position_to_bag', as: 'add_position_to_bag'
  post '/add_escape_to_bag/:id', to: 'bags#add_escape_to_bag', as: 'add_escape_to_bag'


  post '/add_submission_to_bucket/:id', to: 'buckets#add_submission_to_bucket', as: 'add_submission_to_bucket'
  post '/add_position_to_bucket/:id', to: 'buckets#add_position_to_bucket', as: 'add_position_to_bucket'
  post '/add_escape_to_bucket/:id', to: 'buckets#add_escape_to_bucket', as: 'add_escape_to_bucket'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  root to: "home#index" 

end

app/models/escape.rb
class Escape < ApplicationRecord
   belongs_to :bag, optional: true
   belongs_to :bucket, optional: true
end

app/controllers/escapes_controller.rb
class EscapesController < ApplicationController
  before_action :set_escape, only: %i[ show edit update destroy ]

  # GET /escapes or /escapes.json
  def index
    @escapes = Escape.all
  end

  # GET /escapes/1 or /escapes/1.json
  def show
  end

  # GET /escapes/new
  def new
    @escape = Escape.new
  end

  # GET /escapes/1/edit
  def edit
  end

  # POST /escapes or /escapes.json
  def create
    @escape = Escape.new(escape_params)

    respond_to do |format|
      if @escape.save
        format.html { redirect_to escape_url(@escape), notice: "Escape was successfully created." }
        format.json { render :show, status: :created, location: @escape }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @escape.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /escapes/1 or /escapes/1.json
  def update
    respond_to do |format|
      if @escape.update(escape_params)
        format.html { redirect_to escape_url(@escape), notice: "Escape was successfully updated." }
        format.json { render :show, status: :ok, location: @escape }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @escape.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /escapes/1 or /escapes/1.json
  def destroy
    @escape.destroy

    respond_to do |format|
      format.html { redirect_to escapes_url, notice: "Escape was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_escape
      @escape = Escape.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def escape_params
      params.require(:escape).permit(:name, :description, :video_url)
    end
end

app/helpers/escapes_helper.rb
module EscapesHelper
end

app/views/escapes/_form.html.erb
<%= form_with(model: escape) do |form| %>
  <% if escape.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(escape.errors.count, "error") %> prohibited this escape from being saved:</h2>

      <ul>
        <% escape.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :video_url, style: "display: block" %>
    <%= form.text_field :video_url %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/escapes/edit.html.erb
<h1>Editing escape</h1>

<%= render "form", escape: @escape %>

<br>

<div>
  <%= link_to "Show this escape", @escape %> |
  <%= link_to "Back to escapes", escapes_path %>
</div>

app/views/escapes/index.html.erb
<div class="escape">
  <div class="container">
    <div class="row pt-4">
      <% @escapes.take(69).each do |escape| %>
        <div class="col-md-4">
          <%= link_to escape_path(escape) do %>
            <div class="card mb-4" id="<%= dom_id escape %>">
              <div class="card-body">
                <h5 class="card-title"><%= escape.name %></h5>
                <p class="card-text">
                  <strong>Description:</strong> <%= escape.description %> <br>
                </p>
                <iframe loading='lazy' src="https://www.youtube.com/embed/<%= escape.video_url %>?rel=0&autoplay=<%= params[:autoplay] || 0 %>" frameborder="0" allowfullscreen></iframe>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>


<style>
@import url('https://fonts.googleapis.com/css2?family=Righteous&display=swap');
@import url('https://fonts.googleapis.com/css2?family=Lato:wght@300&display=swap');

.escape {
  background-image: url('https://images.unsplash.com/photo-1624398891401-1362e7a0d062?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2232&q=80');
}

.escape a:link{
text-decoration: none;
}

.container {
  -webkit-backdrop-filter: blur(16px) saturate(180%);
  background-color: rgba(17, 25, 40, 0.25);
  border-radius: 12px;
  border: 1px solid rgba(255, 255, 255, 0.125);  
  filter: drop-shadow(0 30px 10px rgba(0,0,0,0.125));
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content:center;
  text-align: center;
}

.card {
  background: transparent;
  border: none;
  border-radius: 20px;
  box-shadow: 2px 2px 8px rgba(0, 0, 0, 0.1);
  overflow: hidden;
  transition: all 0.3s ease-in-out;
  backdrop-filter: blur(15px);
  position: relative;
  padding: 1em;
  color: white;
  text-shadow: 1px 1px 3px rgba(0, 0, 0, 0.2);
}

.card:hover {
  transform: scale(1.05);
  box-shadow: 2px 2px 8px rgba(0, 0, 0, 0.3);
}

.card-body {
  padding: 1.25rem;
}

.card-title {
  font-family: 'Righteous', sans-serif;
  color: rgba(255,255,255,0.98);
  text-transform: uppercase;
  font-size: 2.4rem;
}

.card-text {
  font-family: 'Lato', sans-serif;
  font-size: 0.8rem;
  color: #fff;
  line-height: 150%;
  letter-spacing: 2px;
  text-transform: uppercase;
}

iframe {
  width: 100%;
  height: 200px;
}
</style>

app/views/escapes/new.html.erb
<h1>New escape</h1>

<%= render "form", escape: @escape %>

<br>

<div>
  <%= link_to "Back to escapes", escapes_path %>
</div>

app/views/escapes/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="text-center">

<div class='escape-description'> 
  <div class="card">
    <div class="card-title"> <h5><%= @escape.name%> </h5></div>
    <hr>
    <div class="card-body">
<p class="text-black"> <%= @escape.description%></p>
      </div>

  </div>
</div>
<iframe src="https://www.youtube.com/embed/<%=@escape.video_url %>?rel=0&autoplay=<%= params[:autoplay] || 0 %>" frameborder="0" allowfullscreen></iframe>
</div>

<div class='container'>
 <div class="row">
  <div class="col"> </div>
  <div class="col"> </div>
  <div class="col"> </div>
  <div class="col"> </div>
  <div class="col d-flex justify-content-center">
    <%= button_to "Add to Bag", add_escape_to_bag_path(@escape), method: :post, class: "btn btn-primary" %>
  </div>
  <div class="col d-flex justify-content-center">
    <%= button_to "Add to Bucket", add_escape_to_bucket_path(@escape), method: :post, class: "btn btn-primary" %>
  </div>
  <div class="col d-flex justify-content-center">
    <%= link_to "Back to escapes", escapes_path, class: "btn btn-secondary" %>
  </div>
  <div class="col"> </div>
  <div class="col"> </div>
  <div class="col"> </div>
  <div class="col"> </div>
</div>

</div>

<style>
iframe {
  padding-bottom: 20px;
  width: 80%;
  height: 400px;
}
.card{
  background-color: #FFC23C;
  margin: auto;
  margin-bottom: 10px;
  width: 50%;
}
.card-title{
  margin-top: 10px;
}

</style>